#!/bin/bash
#
# ██      ███████  Lukser (Sergei Lukaushkin)
# ██      ██       Shy. Delicate. Powerful.
# ██      ███████ 
# ██           ██  https://github.com/luks3r
# ███████ ███████  https://gitlab.com/lukser
# 
# A custom bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#############
# AUTOSTART #
#############
[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x picom) ]] && picom &
[[ ! $(pidof -x dunst) ]] && dunst &
#[[ ! $(pidof -x xautolock) ]] && xautolock -time 10 -locker slock &

nitrogen --restore &
#setxkbmap -layout ee,ru -variant us, -option 'grp:alt_shift_toggle'
#. ~/.config/bspwm/panel.sh &

xrandr --output DP-0 --primary --mode 2560x1080 --rate 74.99 --output HDMI-0 --mode 1920x1080 --rate 60.00 --left-of DP-0

#############
# VARIABLES #
#############
bar_height=20
bar_pos=top

padding=0
monocle_padding=-$padding
unfocused=#4c566a
focused=#5e81ac
urgent=#dd2727

############
# MONITORS #############
bspc monitor "HDMI-0" -d 1 2 3 4 5
bspc monitor "DP-0" -d 6 7 8 9 0

#################
# BSPWM CONFIGS #
#################
bspc config border_width 2
bspc config window_gap   10

for side in top right bottom left; do
    if [ $side = $bar_pos ]; then
        bspc config ${side}_padding $padding + $bar_height
    else
        bspc config ${side}_padding $padding
    fi
done


for side in top right bottom left; do
    if [ $side = $bar_pos ]; then
        bspc config ${side}_monocle_padding $monocle_padding + $bar_height
    else
        bspc config ${side}_monocle_padding $monocle_padding
    fi
done

bspc config single_monocle             false
bspc config click_to_focus             false
bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config history_aware_focus        true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

##################
# BSPWM COLORING #
##################
# All these are temporary
bspc config normal_border_color	  $unfocused
bspc config active_border_color   $unfocused
bspc config focused_border_color  $focused
bspc config presel_feedback_color $focused 
bspc config urgent_border_color   $urgent

###################
# POLYBAR HELPERS #
###################
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

###############
# BSPWM RULES #
###############
bspc rule -a firefox desktop=web
bspc rule -a utox desktop=chat follow=off
bspc rule -a discord desktop=chat follow=off
bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop=code state=tiled follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Alacritty:pulsemixer state=floating
bspc rule -a Alacritty:ncmpcpp desktop=media
bspc rule -a Keybase desktop=chat
bspc rule --add Telegram:Telegram --one-shot; telegram >/dev/null &

###############
# SET WM NAME #
###############
export _JAVA_AWT_WM_NONREPARENTING=1 
#export AWT_TOOLKIT=MToolkit
wmname LG3D

